services:
  # Layanan untuk NestJS API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network

  # Layanan untuk MariaDB
  db:
    image: mariadb:latest
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '000000'
      MYSQL_DATABASE: 'lms'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
